/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.PopupMenu;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thobakgale Decent
 */
public class personalForm extends javax.swing.JFrame {

    /**
     * Creates new form personalForm
     */
    public personalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel22 = new javax.swing.JLabel();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        RadFemale = new javax.swing.JRadioButton();
        RadMale = new javax.swing.JRadioButton();
        RadLGBT = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        txtDisability = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        RadYes = new javax.swing.JRadioButton();
        RadNo = new javax.swing.JRadioButton();
        LblName = new javax.swing.JLabel();
        LblPhone = new javax.swing.JLabel();
        LblAddress = new javax.swing.JLabel();
        LblGender = new javax.swing.JLabel();
        LblCrime = new javax.swing.JLabel();
        LblDisabilities = new javax.swing.JLabel();
        LblLastname = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        LblAge = new javax.swing.JLabel();
        LblDisability = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnChk = new javax.swing.JCheckBox();
        BtnHelp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnLight = new javax.swing.JButton();
        BtnDark = new javax.swing.JButton();
        LblAgee = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        LblIDD = new javax.swing.JLabel();
        ChckShow = new javax.swing.JCheckBox();

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONAL DETAILS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("NAME");

        jLabel2.setText("LASTNAME");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel3.setText("EMAIL");

        jLabel4.setText("PHONE");

        jLabel5.setText("PHYSICAL ADDRESS");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("                                           PERSONAL DETAILS");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel12.setText("ID");

        jLabel13.setText("AGE");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("     MICROSOFT STUDIOS APLLICATION FORM");

        jLabel15.setText("GENDER");

        jLabel18.setText("PASSWORD");

        RadFemale.setText("FEMALE");
        RadFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadFemaleActionPerformed(evt);
            }
        });

        RadMale.setText("MALE");
        RadMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadMaleActionPerformed(evt);
            }
        });

        RadLGBT.setText("LGBT");
        RadLGBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadLGBTActionPerformed(evt);
            }
        });

        jLabel23.setText("DISABILITIES");

        jLabel24.setText("CRIMINAL RECORD");

        RadYes.setText("YES");
        RadYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadYesActionPerformed(evt);
            }
        });

        RadNo.setText("NO");
        RadNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadNoActionPerformed(evt);
            }
        });

        LblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblCrime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblLastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LblDisability.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChkActionPerformed(evt);
            }
        });

        BtnHelp.setText("ASSISTANCE");
        BtnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHelpActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("                                           VERIFICATION");

        BtnLight.setText("LIGHT");
        BtnLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLightActionPerformed(evt);
            }
        });

        BtnDark.setText("DARK");
        BtnDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(BtnHelp)
                .addGap(64, 64, 64)
                .addComponent(BtnChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnDark)
                .addGap(42, 42, 42)
                .addComponent(BtnLight))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(BtnSave)
                        .addComponent(BtnHelp))
                    .addComponent(BtnChk)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnDark)
                        .addComponent(BtnLight)))
                .addGap(14, 14, 14))
        );

        LblAgee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        LblIDD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ChckShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChckShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LblLastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(txtLastname)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(LblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(LblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                                    .addComponent(LblAgee, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(LblIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChckShow))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblDisabilities, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(18, 18, 18)
                                                .addComponent(RadYes))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPhone)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                                    .addComponent(LblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(LblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtDisability)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(LblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(RadFemale)
                                                            .addGap(18, 18, 18)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(RadNo)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(RadMale)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(RadLGBT))))))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChckShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(RadFemale)
                                .addComponent(RadMale)
                                .addComponent(RadLGBT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(RadYes)
                                    .addComponent(RadNo)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblDisabilities, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblAge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtDisability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblAgee, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        String NAMES = txtName.getText(), LASTNAME = txtLastname.getText(), EMAIL = txtEmail.getText(), ID = txtID.getText();
        String PASSWORD = txtPassword.getText();
        String AGE = txtAge.getText(), PHONE = txtPhone.getText();
        String ADDRESS = txtAddress.getText(), DISABILITIES = txtDisability.getText();  
        
        if(txtName.getText().isEmpty() && txtLastname.getText().isEmpty() && txtLastname.getText().isEmpty() && txtEmail.getText().isEmpty() 
                && txtPhone.getText().isEmpty() && txtID.getText().isEmpty() && txtAddress.getText().isEmpty()
                && txtDisability.getText().isEmpty() && txtPassword.getText().isEmpty() && txtAge.getText().isEmpty()){
            
            LblName.setText("Invalid"); LblName.setForeground(Color.red); LblLastname.setText("Invalid"); LblLastname.setForeground(Color.red);
            LblEmail.setText("Invalid"); LblEmail.setForeground(Color.red); LblDisability.setText("Invalid"); LblDisability.setForeground(Color.red);
            LblPhone.setText("Invalid"); LblPhone.setForeground(Color.red); LblIDD.setText("Invalid"); LblIDD.setForeground(Color.red);
            LblAddress.setText("Invalid"); LblAddress.setForeground(Color.red); LblPassword.setText("Invalid"); LblPassword.setForeground(Color.red);
            LblAgee.setText("Invalid"); LblAgee.setForeground(Color.red); LblGender.setText("Invalid"); LblGender.setForeground(Color.red);  
            LblCrime.setText("Invalid"); LblCrime.setForeground(Color.red);
        }
       else if(!NAMES.matches("[a-zA-Z]+") || NAMES.length() < 3){
            LblName.setText("Atleast 3 Characters with no letters");
            LblName.setForeground(Color.yellow);
        }
        else if(LASTNAME.length() < 3 || !LASTNAME.matches("[a-zA-Z]+")){
            LblLastname.setText("Atleast 3 Characters");
            LblLastname.setForeground(Color.yellow);
        }
        else if(!EMAIL.contains("@gmail.com")){
            LblEmail.setText("Invalid email");
            LblEmail.setForeground(Color.yellow);
        }
        else if(ID.length() < 13 || ID.length() > 13){
            LblIDD.setText("13 digits/characters");
            LblIDD.setForeground(Color.yellow);
        }
        else if(!AGE.matches("[0-9]+") || AGE.length() < 2 || AGE.length() > 2){
            LblAgee.setText("2 integers only");
            LblAgee.setForeground(Color.yellow);
        }
        else if(PHONE.length() < 10 || PHONE.length() >10 || !PHONE.matches("[0-9]+") || !PHONE.startsWith("0")){
            LblPhone.setText("Must start with a 0 and contain 10 integers only");
            LblPhone.setForeground(Color.yellow);
        }
        else if(!ADDRESS.contains("street") && !ADDRESS.contains("[a-zA-Z0-9]+")){
             LblAddress.setText("Must contain street and number");
             LblAddress.setForeground(Color.yellow);
        }
        else if(!DISABILITIES.equalsIgnoreCase("yes") && !DISABILITIES.equalsIgnoreCase("no")){
            LblDisability.setText("Enter yes or no, if yes please specify your disability");
            LblDisability.setForeground(Color.yellow); 
        }
        else if(!RadFemale.isSelected() && !RadMale.isSelected() && !RadLGBT.isSelected() && !RadYes.isSelected() 
                && !RadNo.isSelected()){
            LblGender.setText("Select one button");
            LblGender.setForeground(Color.yellow);
            LblCrime.setText("Select one button");
            LblCrime.setForeground(Color.yellow);
        }
        else if(RadYes.isSelected()){
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "You can't carry on with the application because you have a criminal record");
        }
        else if(PASSWORD.length() < 8){
            LblPassword.setText("Must be 8 characters long, with one uppercase,& one digit");
            LblPassword.setForeground(Color.yellow);
        }
        else {
            LblDisability.setText("Valid"); LblDisability.setForeground(Color.GREEN); LblIDD.setText("Valid"); LblIDD.setForeground(Color.GREEN); 
            LblLastname.setText("Valid"); LblLastname.setForeground(Color.GREEN); LblPhone.setText("Valid"); 
            LblPhone.setForeground(Color.GREEN); LblAddress.setText("Valid"); LblAddress.setForeground(Color.GREEN); 
            LblName.setText("Valid"); LblName.setForeground(Color.GREEN); LblAgee.setText("Valid"); 
            LblAgee.setForeground(Color.GREEN); LblEmail.setText("Valid"); LblEmail.setForeground(Color.GREEN);
            LblGender.setText("Valid"); LblGender.setForeground(Color.GREEN); LblCrime.setText("Valid"); 
            LblCrime.setForeground(Color.GREEN); LblPassword.setText("Valid"); LblPassword.setForeground(Color.GREEN);
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Confirm that you are not a robot");
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
       
    }//GEN-LAST:event_txtAgeActionPerformed

    private void BtnChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChkActionPerformed
       
        if(txtName.getText().isEmpty() || txtLastname.getText().isEmpty() || txtEmail.getText().isEmpty() 
                || txtPhone.getText().isEmpty() || txtID.getText().isEmpty() || txtAddress.getText().isEmpty()
                || txtPassword.getText().isEmpty() || txtAge.getText().isEmpty() || RadYes.isSelected()){
            
            BtnChk.setSelected(false);
        }
        else{
            new educationForm().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnChkActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Component frame = null;
        int choice = JOptionPane.showOptionDialog(frame, "Select a field", "Clear Options",
                JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                null, 
                new String[]{"Clear All", "Clear Section", "Cancel"},
                "Clear" + "");
        if(choice == 0){
            txtName.setText(""); LblName.setText(""); txtLastname.setText(""); LblLastname.setText(""); 
            txtEmail.setText(""); LblEmail.setText(""); txtPhone.setText(""); LblPhone.setText(""); txtID.setText("");
            LblIDD.setText(""); LblCrime.setText(""); LblGender.setText(""); 
            txtAddress.setText(""); LblAddress.setText(""); txtPassword.setText(""); LblPassword.setText(""); 
            txtAge.setText(""); LblAgee.setText(""); txtDisability.setText(""); LblDisability.setText("");
        }
        else if(choice == 1){
            String section = JOptionPane.showInputDialog("Enter field to clear");
            if(section.equalsIgnoreCase("name")){ 
                txtName.setText(""); LblName.setText("");
            }
            else if(section.equalsIgnoreCase("lastname")){
                txtLastname.setText(""); LblLastname.setText(""); 
            }
            else if(section.equalsIgnoreCase("email")){
                txtEmail.setText(""); LblEmail.setText("");
            }
            else if(section.equalsIgnoreCase("ID")){
                txtID.setText(""); LblIDD.setText("");
            }
            else if(section.equalsIgnoreCase("physical address")){
                txtAddress.setText(""); LblAddress.setText("");
            }
            else if(section.equalsIgnoreCase("password")){
                txtPassword.setText(""); LblPassword.setText("");
            }
            else if(section.equalsIgnoreCase("age")){
                txtAge.setText(""); LblAgee.setText("");
            }
            else if(section.equalsIgnoreCase("disabilities")){
                txtDisability.setText(""); LblDisability.setText("");
            }
            else if(section.equalsIgnoreCase("phone")){
                txtPhone.setText(""); LblPhone.setText("");
            }
            else{
                JOptionPane.showMessageDialog(frame, "invalid");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RadMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadMaleActionPerformed
        // TODO add your handling code here:
        if(RadMale.isSelected())
            RadFemale.setSelected(false);
             RadLGBT.setSelected(false);
    }//GEN-LAST:event_RadMaleActionPerformed

    private void RadFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadFemaleActionPerformed

        if(RadFemale.isSelected())
            RadMale.setSelected(false);
             RadLGBT.setSelected(false);
        
    }//GEN-LAST:event_RadFemaleActionPerformed

    private void RadLGBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadLGBTActionPerformed
        // TODO add your handling code here:
        if(RadLGBT.isSelected())
            RadMale.setSelected(false);
             RadFemale.setSelected(false);
    }//GEN-LAST:event_RadLGBTActionPerformed

    private void RadYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadYesActionPerformed
       
        if(RadYes.isSelected())
            RadNo.setSelected(false);
    }//GEN-LAST:event_RadYesActionPerformed

    private void RadNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadNoActionPerformed
        // TODO add your handling code here:
        if(RadNo.isSelected())
            RadYes.setSelected(false);
    }//GEN-LAST:event_RadNoActionPerformed

    private void BtnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHelpActionPerformed
        new personalHelp().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnHelpActionPerformed

    private void ChckShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChckShowActionPerformed
        if(txtPassword.getText().isBlank()){
            ChckShow.setSelected(false);
        }
        else if(ChckShow.isSelected()){
            txtPassword.setEchoChar((char )0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ChckShowActionPerformed

    private void BtnLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLightActionPerformed
        jPanel1.setBackground(Color.white); 
    }//GEN-LAST:event_BtnLightActionPerformed

    private void BtnDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDarkActionPerformed
        jPanel1.setBackground(Color.gray); 
    }//GEN-LAST:event_BtnDarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BtnChk;
    private javax.swing.JButton BtnDark;
    private javax.swing.JButton BtnHelp;
    private javax.swing.JButton BtnLight;
    private javax.swing.JButton BtnSave;
    private javax.swing.JCheckBox ChckShow;
    private javax.swing.JLabel LblAddress;
    private javax.swing.JLabel LblAge;
    private javax.swing.JLabel LblAgee;
    private javax.swing.JLabel LblCrime;
    private javax.swing.JLabel LblDisabilities;
    private javax.swing.JLabel LblDisability;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblGender;
    private javax.swing.JLabel LblIDD;
    private javax.swing.JLabel LblLastname;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JRadioButton RadFemale;
    private javax.swing.JRadioButton RadLGBT;
    private javax.swing.JRadioButton RadMale;
    private javax.swing.JRadioButton RadNo;
    private javax.swing.JRadioButton RadYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDisability;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private boolean hasLowercase(String Password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private boolean hasDigit(String Password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private boolean hasUppercase(String Password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
